SELECT DISTINCT `T_PRODUCT`.`name` as `product_name`, `T_PRODUCT`.`vrepeat`, `T_PRODUCT`.`hrepeat`, `T_PRODUCT`.`width` as `width`, `T_PRODUCT`.`id`, `T_PRODUCT`.`outdoor`, 'R' as product_type, `T_PRODUCT`.`archived`, GROUP_CONCAT(DISTINCT T_PRODUCT_ABRASION.abrasion_test_id, '*', `P_ABRASION_LIMIT`.`name`, '-', `T_PRODUCT_ABRASION`.`n_rubs`, '-', P_ABRASION_TEST.name SEPARATOR ' / ') as abrasions, COUNT(DISTINCT T_PRODUCT_ABRASION_FILES.abrasion_id) as count_abrasion_files, GROUP_CONCAT(DISTINCT REPLACE(T_PRODUCT_CONTENT_FRONT.perc, '.00', ''), '% ', PC1.name ORDER BY T_PRODUCT_CONTENT_FRONT.perc DESC SEPARATOR ' / ' ) as content_front, GROUP_CONCAT(DISTINCT P_FIRECODE_TEST.name SEPARATOR ' / ') as firecodes, COUNT(DISTINCT T_PRODUCT_FIRECODE_FILES.firecode_id) as count_firecode_files, GROUP_CONCAT(DISTINCT P_SHELF.name ORDER BY P_SHELF.name ASC SEPARATOR ' / ') as shelf, GROUP_CONCAT(DISTINCT P_SHELF.id SEPARATOR ' / ') as shelf_id, GROUP_CONCAT(DISTINCT P_USE.name ORDER BY P_USE.name ASC SEPARATOR ' / ') as uses, GROUP_CONCAT(DISTINCT P_USE.id SEPARATOR ' / ') as uses_id, `V`.`name` as `vendors_name`, `V`.`abrev` as `vendors_abrev`, GROUP_CONCAT(DISTINCT P_WEAVE.name ORDER BY P_WEAVE.name ASC SEPARATOR ' / ') as weaves, GROUP_CONCAT(DISTINCT P_WEAVE.id SEPARATOR ' / ') as weaves_id
FROM `T_PRODUCT`
LEFT OUTER JOIN `T_PRODUCT_ABRASION` ON `T_PRODUCT`.`id` = `T_PRODUCT_ABRASION`.`product_id`
LEFT OUTER JOIN `P_ABRASION_TEST` ON `T_PRODUCT_ABRASION`.`abrasion_test_id` = `P_ABRASION_TEST`.`id`
LEFT OUTER JOIN `P_ABRASION_LIMIT` ON `T_PRODUCT_ABRASION`.`abrasion_limit_id` = `P_ABRASION_LIMIT`.`id`
LEFT OUTER JOIN `T_PRODUCT_ABRASION_FILES` ON `T_PRODUCT_ABRASION`.`id` = `T_PRODUCT_ABRASION_FILES`.`abrasion_id`
LEFT OUTER JOIN `T_PRODUCT_CONTENT_FRONT` ON `T_PRODUCT`.`id` = `T_PRODUCT_CONTENT_FRONT`.`product_id`
LEFT OUTER JOIN `P_CONTENT` `PC1` ON `T_PRODUCT_CONTENT_FRONT`.`content_id` = `PC1`.`id`
LEFT OUTER JOIN `T_PRODUCT_FIRECODE` ON `T_PRODUCT`.`id` = `T_PRODUCT_FIRECODE`.`product_id`
LEFT OUTER JOIN `P_FIRECODE_TEST` ON `T_PRODUCT_FIRECODE`.`firecode_test_id` = `P_FIRECODE_TEST`.`id`
LEFT OUTER JOIN `T_PRODUCT_FIRECODE_FILES` ON `T_PRODUCT_FIRECODE`.`id` = `T_PRODUCT_FIRECODE_FILES`.`firecode_id`
LEFT OUTER JOIN `T_PRODUCT_SHELF` ON `T_PRODUCT`.`id` = `T_PRODUCT_SHELF`.`product_id` AND `T_PRODUCT_SHELF`.`product_type` = 'R' 
LEFT OUTER JOIN `P_SHELF` ON `T_PRODUCT_SHELF`.`shelf_id` = `P_SHELF`.`id`
LEFT OUTER JOIN `T_PRODUCT_USE` ON `T_PRODUCT`.`id` = `T_PRODUCT_USE`.`product_id`
LEFT OUTER JOIN `P_USE` ON `T_PRODUCT_USE`.`use_id` = `P_USE`.`id`
LEFT OUTER JOIN `T_PRODUCT_VENDOR` ON `T_PRODUCT`.`id` = `T_PRODUCT_VENDOR`.`product_id`
LEFT OUTER JOIN `Z_VENDOR` `V` ON `T_PRODUCT_VENDOR`.`vendor_id` = `V`.`id`
LEFT OUTER JOIN `T_PRODUCT_WEAVE` ON `T_PRODUCT`.`id` = `T_PRODUCT_WEAVE`.`product_id`
LEFT OUTER JOIN `P_WEAVE` ON `T_PRODUCT_WEAVE`.`weave_id` = `P_WEAVE`.`id`
GROUP BY `T_PRODUCT`.`id` 

UNION ALL 


SELECT DISTINCT CONCAT(
							U_DIGITAL_STYLE.name, ' on ', CASE WHEN T_PRODUCT_X_DIGITAL.reverse_ground = 'Y' THEN 'Reverse ' ELSE '' END, COALESCE(T_PRODUCT.dig_product_name, T_PRODUCT.name), ' / ', GROUP_CONCAT(DISTINCT P_COLOR.name SEPARATOR ' / ') 
						) as product_name, `U_DIGITAL_STYLE`.`vrepeat`, `U_DIGITAL_STYLE`.`hrepeat`, COALESCE(T_PRODUCT.dig_width, T_PRODUCT.width) as width, `T_PRODUCT_X_DIGITAL`.`id`, `T_PRODUCT`.`outdoor`, 'D' as product_type, `T_PRODUCT_X_DIGITAL`.`archived`, GROUP_CONCAT(DISTINCT T_PRODUCT_ABRASION.abrasion_test_id, '*', `P_ABRASION_LIMIT`.`name`, '-', `T_PRODUCT_ABRASION`.`n_rubs`, '-', P_ABRASION_TEST.name SEPARATOR ' / ') as abrasions, COUNT(DISTINCT T_PRODUCT_ABRASION_FILES.abrasion_id) as count_abrasion_files, GROUP_CONCAT(DISTINCT REPLACE(T_PRODUCT_CONTENT_FRONT.perc, '.00', ''), '% ', PC1.name ORDER BY T_PRODUCT_CONTENT_FRONT.perc DESC SEPARATOR ' / ' ) as content_front, GROUP_CONCAT(DISTINCT P_FIRECODE_TEST.name SEPARATOR ' / ') as firecodes, COUNT(DISTINCT T_PRODUCT_FIRECODE_FILES.firecode_id) as count_firecode_files, GROUP_CONCAT(DISTINCT P_SHELF.name ORDER BY P_SHELF.name ASC SEPARATOR ' / ') as shelf, GROUP_CONCAT(DISTINCT P_SHELF.id SEPARATOR ' / ') as shelf_id, GROUP_CONCAT(DISTINCT P_USE.name ORDER BY P_USE.name ASC SEPARATOR ' / ') as uses, GROUP_CONCAT(DISTINCT P_USE.id SEPARATOR ' / ') as uses_id, `V`.`name` as `vendors_name`, `V`.`abrev` as `vendors_abrev`, GROUP_CONCAT(DISTINCT P_WEAVE.name ORDER BY P_WEAVE.name ASC SEPARATOR ' / ') as weaves, GROUP_CONCAT(DISTINCT P_WEAVE.id SEPARATOR ' / ') as weaves_id
FROM (`T_ITEM`, `T_PRODUCT`, `U_DIGITAL_STYLE`, `T_PRODUCT_X_DIGITAL`)
LEFT OUTER JOIN `T_ITEM_COLOR` ON `T_ITEM_COLOR`.`item_id` = `T_ITEM`.`id`
LEFT OUTER JOIN `P_COLOR` ON `P_COLOR`.`id` = `T_ITEM_COLOR`.`color_id`
LEFT OUTER JOIN `T_PRODUCT_ABRASION` ON `T_PRODUCT`.`id` = `T_PRODUCT_ABRASION`.`product_id`
LEFT OUTER JOIN `P_ABRASION_TEST` ON `T_PRODUCT_ABRASION`.`abrasion_test_id` = `P_ABRASION_TEST`.`id`
LEFT OUTER JOIN `P_ABRASION_LIMIT` ON `T_PRODUCT_ABRASION`.`abrasion_limit_id` = `P_ABRASION_LIMIT`.`id`
LEFT OUTER JOIN `T_PRODUCT_ABRASION_FILES` ON `T_PRODUCT_ABRASION`.`id` = `T_PRODUCT_ABRASION_FILES`.`abrasion_id`
LEFT OUTER JOIN `T_PRODUCT_CONTENT_FRONT` ON `T_PRODUCT`.`id` = `T_PRODUCT_CONTENT_FRONT`.`product_id`
LEFT OUTER JOIN `P_CONTENT` `PC1` ON `T_PRODUCT_CONTENT_FRONT`.`content_id` = `PC1`.`id`
LEFT OUTER JOIN `T_PRODUCT_FIRECODE` ON `T_PRODUCT`.`id` = `T_PRODUCT_FIRECODE`.`product_id`
LEFT OUTER JOIN `P_FIRECODE_TEST` ON `T_PRODUCT_FIRECODE`.`firecode_test_id` = `P_FIRECODE_TEST`.`id`
LEFT OUTER JOIN `T_PRODUCT_FIRECODE_FILES` ON `T_PRODUCT_FIRECODE`.`id` = `T_PRODUCT_FIRECODE_FILES`.`firecode_id`
LEFT OUTER JOIN `T_PRODUCT_SHELF` ON `T_PRODUCT_X_DIGITAL`.`id` = `T_PRODUCT_SHELF`.`product_id` AND `T_PRODUCT_SHELF`.`product_type` = 'D' 
LEFT OUTER JOIN `P_SHELF` ON `T_PRODUCT_SHELF`.`shelf_id` = `P_SHELF`.`id`
LEFT OUTER JOIN `T_PRODUCT_USE` ON `T_PRODUCT`.`id` = `T_PRODUCT_USE`.`product_id`
LEFT OUTER JOIN `P_USE` ON `T_PRODUCT_USE`.`use_id` = `P_USE`.`id`
LEFT OUTER JOIN `T_PRODUCT_VENDOR` ON `T_PRODUCT`.`id` = `T_PRODUCT_VENDOR`.`product_id`
LEFT OUTER JOIN `Z_VENDOR` `V` ON `T_PRODUCT_VENDOR`.`vendor_id` = `V`.`id`
LEFT OUTER JOIN `T_PRODUCT_WEAVE` ON `T_PRODUCT`.`id` = `T_PRODUCT_WEAVE`.`product_id`
LEFT OUTER JOIN `P_WEAVE` ON `T_PRODUCT_WEAVE`.`weave_id` = `P_WEAVE`.`id`
WHERE `T_PRODUCT_X_DIGITAL`.`item_id` = `T_ITEM`.`id`
AND `T_PRODUCT`.`id` = `T_ITEM`.`product_id`
AND `T_PRODUCT_X_DIGITAL`.`style_id` = `U_DIGITAL_STYLE`.`id`
GROUP BY `T_PRODUCT_X_DIGITAL`.`id` 

UNION ALL 

SELECT DISTINCT CONCAT(
							U_SCREENPRINT_STYLE.name, ' on ', CASE WHEN T_PRODUCT_X_SCREENPRINT.reverse_ground = 'Y' THEN 'Reverse ' ELSE '' END, `T_PRODUCT`.`name`, ' / ', GROUP_CONCAT(DISTINCT P_COLOR.name SEPARATOR ' / ') 
						) as product_name, `U_SCREENPRINT_STYLE`.`vrepeat`, `U_SCREENPRINT_STYLE`.`hrepeat`, `T_PRODUCT`.`width` as `width`, `T_PRODUCT_X_SCREENPRINT`.`id`, `T_PRODUCT`.`outdoor`, 'SP' as product_type, `T_PRODUCT_X_SCREENPRINT`.`archived`, GROUP_CONCAT(DISTINCT T_PRODUCT_ABRASION.abrasion_test_id, '*', `P_ABRASION_LIMIT`.`name`, '-', `T_PRODUCT_ABRASION`.`n_rubs`, '-', P_ABRASION_TEST.name SEPARATOR ' / ') as abrasions, COUNT(DISTINCT T_PRODUCT_ABRASION_FILES.abrasion_id) as count_abrasion_files, GROUP_CONCAT(DISTINCT REPLACE(T_PRODUCT_CONTENT_FRONT.perc, '.00', ''), '% ', PC1.name ORDER BY T_PRODUCT_CONTENT_FRONT.perc DESC SEPARATOR ' / ' ) as content_front, GROUP_CONCAT(DISTINCT P_FIRECODE_TEST.name SEPARATOR ' / ') as firecodes, COUNT(DISTINCT T_PRODUCT_FIRECODE_FILES.firecode_id) as count_firecode_files, GROUP_CONCAT(DISTINCT P_SHELF.name ORDER BY P_SHELF.name ASC SEPARATOR ' / ') as shelf, GROUP_CONCAT(DISTINCT P_SHELF.id SEPARATOR ' / ') as shelf_id, GROUP_CONCAT(DISTINCT P_USE.name ORDER BY P_USE.name ASC SEPARATOR ' / ') as uses, GROUP_CONCAT(DISTINCT P_USE.id SEPARATOR ' / ') as uses_id, `V`.`name` as `vendors_name`, `V`.`abrev` as `vendors_abrev`, GROUP_CONCAT(DISTINCT P_WEAVE.name ORDER BY P_WEAVE.name ASC SEPARATOR ' / ') as weaves, GROUP_CONCAT(DISTINCT P_WEAVE.id SEPARATOR ' / ') as weaves_id
FROM (`T_ITEM`, `T_PRODUCT`, `U_SCREENPRINT_STYLE`, `T_PRODUCT_X_SCREENPRINT`)
LEFT OUTER JOIN `T_ITEM_COLOR` ON `T_ITEM_COLOR`.`item_id` = `T_ITEM`.`id`
LEFT OUTER JOIN `P_COLOR` ON `P_COLOR`.`id` = `T_ITEM_COLOR`.`color_id`
LEFT OUTER JOIN `T_PRODUCT_ABRASION` ON `T_PRODUCT`.`id` = `T_PRODUCT_ABRASION`.`product_id`
LEFT OUTER JOIN `P_ABRASION_TEST` ON `T_PRODUCT_ABRASION`.`abrasion_test_id` = `P_ABRASION_TEST`.`id`
LEFT OUTER JOIN `P_ABRASION_LIMIT` ON `T_PRODUCT_ABRASION`.`abrasion_limit_id` = `P_ABRASION_LIMIT`.`id`
LEFT OUTER JOIN `T_PRODUCT_ABRASION_FILES` ON `T_PRODUCT_ABRASION`.`id` = `T_PRODUCT_ABRASION_FILES`.`abrasion_id`
LEFT OUTER JOIN `T_PRODUCT_CONTENT_FRONT` ON `T_PRODUCT`.`id` = `T_PRODUCT_CONTENT_FRONT`.`product_id`
LEFT OUTER JOIN `P_CONTENT` `PC1` ON `T_PRODUCT_CONTENT_FRONT`.`content_id` = `PC1`.`id`
LEFT OUTER JOIN `T_PRODUCT_FIRECODE` ON `T_PRODUCT`.`id` = `T_PRODUCT_FIRECODE`.`product_id`
LEFT OUTER JOIN `P_FIRECODE_TEST` ON `T_PRODUCT_FIRECODE`.`firecode_test_id` = `P_FIRECODE_TEST`.`id`
LEFT OUTER JOIN `T_PRODUCT_FIRECODE_FILES` ON `T_PRODUCT_FIRECODE`.`id` = `T_PRODUCT_FIRECODE_FILES`.`firecode_id`
LEFT OUTER JOIN `T_PRODUCT_SHELF` ON `T_PRODUCT_X_SCREENPRINT`.`id` = `T_PRODUCT_SHELF`.`product_id` AND `T_PRODUCT_SHELF`.`product_type` = 'SP' 
LEFT OUTER JOIN `P_SHELF` ON `T_PRODUCT_SHELF`.`shelf_id` = `P_SHELF`.`id`
LEFT OUTER JOIN `T_PRODUCT_USE` ON `T_PRODUCT`.`id` = `T_PRODUCT_USE`.`product_id`
LEFT OUTER JOIN `P_USE` ON `T_PRODUCT_USE`.`use_id` = `P_USE`.`id`
LEFT OUTER JOIN `T_PRODUCT_VENDOR` ON `T_PRODUCT`.`id` = `T_PRODUCT_VENDOR`.`product_id`
LEFT OUTER JOIN `Z_VENDOR` `V` ON `T_PRODUCT_VENDOR`.`vendor_id` = `V`.`id`
LEFT OUTER JOIN `T_PRODUCT_WEAVE` ON `T_PRODUCT`.`id` = `T_PRODUCT_WEAVE`.`product_id`
LEFT OUTER JOIN `P_WEAVE` ON `T_PRODUCT_WEAVE`.`weave_id` = `P_WEAVE`.`id`
WHERE `T_PRODUCT_X_SCREENPRINT`.`item_id` = `T_ITEM`.`id`
AND `T_PRODUCT`.`id` = `T_ITEM`.`product_id`
AND `T_PRODUCT_X_SCREENPRINT`.`style_id` = `U_SCREENPRINT_STYLE`.`id`
GROUP BY `T_PRODUCT_X_SCREENPRINT`.`id`